---
- name: Remove old toolchain
  become: true
  file:
    path: "{{ golang_toolchain_final_dest }}"
    state: absent
  when:
    - toolchain_archive_contents.changed

- name: Move golang directory from tmp to opt
  become: true
  command: mv /tmp/golang {{ golang_toolchain_final_dest }}
  when:
    - toolchain_archive_contents.changed

- name: Create version file
  become: true
  copy:
    content: "{{ golang_toolchain_sha }}"
    dest: "{{ golang_toolchain_final_dest }}/toolchain_version"
