---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian9
    image: debian:9
  - name: rhel8
    image: registry.redhat.io/ubi8
  - name: rhel7
    image: registry.redhat.io/ubi7
provisioner:
  name: ansible
verifier:
  name: testinfra
