---
- become: true
  name: Converge
  hosts: all
  roles:
    - role: ansible-role-golang-toolchain
      vars:
        golang_toolchain_dest: /opt
        golang_toolchain_sha: 001ac697f8f64d5d89625373a0ffa6aae13270a8
