---
- gather_facts: false
  name: Create
  hosts: all
  tasks:
    - name: Create golang test directory
      file:
        path: /tmp/golang_test
        state: directory
        mode: 0755
        owner: root
        group: root
